//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.1433
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace littleRunner.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("littleRunner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/Background/blue_hills.png ähnelt.
        /// </summary>
        internal static string blue_hills {
            get {
                return ResourceManager.GetString("blue_hills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/Box/box1.png ähnelt.
        /// </summary>
        internal static string box1 {
            get {
                return ResourceManager.GetString("box1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/Brick/brick_blue.png ähnelt.
        /// </summary>
        internal static string brick_blue {
            get {
                return ResourceManager.GetString("brick_blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/Brick/brick_ice.png ähnelt.
        /// </summary>
        internal static string brick_ice {
            get {
                return ResourceManager.GetString("brick_ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/Brick/brick_red.png ähnelt.
        /// </summary>
        internal static string brick_red {
            get {
                return ResourceManager.GetString("brick_red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/Brick/brick_yellow.png ähnelt.
        /// </summary>
        internal static string brick_yellow {
            get {
                return ResourceManager.GetString("brick_yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/GameElement/fire.png ähnelt.
        /// </summary>
        internal static string fire {
            get {
                return ResourceManager.GetString("fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/GameItem/fire_flower.png ähnelt.
        /// </summary>
        internal static string fire_flower {
            get {
                return ResourceManager.GetString("fire_flower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/Floor/floor_left.png ähnelt.
        /// </summary>
        internal static string floor_left {
            get {
                return ResourceManager.GetString("floor_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/Floor/floor.png ähnelt.
        /// </summary>
        internal static string floor_middle {
            get {
                return ResourceManager.GetString("floor_middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/Floor/floor_right.png ähnelt.
        /// </summary>
        internal static string floor_right {
            get {
                return ResourceManager.GetString("floor_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/Background/green_hills.png ähnelt.
        /// </summary>
        internal static string green_hills {
            get {
                return ResourceManager.GetString("green_hills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/Enemie/Gumba/brown.gif ähnelt.
        /// </summary>
        internal static string gumba_brown {
            get {
                return ResourceManager.GetString("gumba_brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/Main/TuxIcon.png ähnelt.
        /// </summary>
        internal static string icon_png {
            get {
                return ResourceManager.GetString("icon_png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/LevelEnd/house.png ähnelt.
        /// </summary>
        internal static string levelend_house {
            get {
                return ResourceManager.GetString("levelend_house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/GameItem/mushroom_green.png ähnelt.
        /// </summary>
        internal static string mushroom_green {
            get {
                return ResourceManager.GetString("mushroom_green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/GameItem/mushroom_poison.png ähnelt.
        /// </summary>
        internal static string mushroom_poison {
            get {
                return ResourceManager.GetString("mushroom_poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/Pipe/pipe_green_main.png ähnelt.
        /// </summary>
        internal static string pipe_green_main {
            get {
                return ResourceManager.GetString("pipe_green_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/Pipe/pipe_green_up.png ähnelt.
        /// </summary>
        internal static string pipe_green_up {
            get {
                return ResourceManager.GetString("pipe_green_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/Enemie/Spika/green.png ähnelt.
        /// </summary>
        internal static string spika_green {
            get {
                return ResourceManager.GetString("spika_green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/Enemie/Spika/grey.png ähnelt.
        /// </summary>
        internal static string spika_grey {
            get {
                return ResourceManager.GetString("spika_grey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/Enemie/Spika/orange.png ähnelt.
        /// </summary>
        internal static string spika_orange {
            get {
                return ResourceManager.GetString("spika_orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/GameItem/star.png ähnelt.
        /// </summary>
        internal static string star {
            get {
                return ResourceManager.GetString("star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/GameElement/tree.png ähnelt.
        /// </summary>
        internal static string tree {
            get {
                return ResourceManager.GetString("tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/Enemie/Turtle/Green/turtle_down.png ähnelt.
        /// </summary>
        internal static string turtle_green_down {
            get {
                return ResourceManager.GetString("turtle_green_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/Enemie/Turtle/Green/turtle_left.gif ähnelt.
        /// </summary>
        internal static string turtle_green_left {
            get {
                return ResourceManager.GetString("turtle_green_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/Enemie/Turtle/Green/turtle_right.gif ähnelt.
        /// </summary>
        internal static string turtle_green_right {
            get {
                return ResourceManager.GetString("turtle_green_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/MainGameObject/Tux/tux_left.gif ähnelt.
        /// </summary>
        internal static string tux_left {
            get {
                return ResourceManager.GetString("tux_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/Images/MainGameObject/Tux/tux_right.gif ähnelt.
        /// </summary>
        internal static string tux_right {
            get {
                return ResourceManager.GetString("tux_right", resourceCulture);
            }
        }
    }
}
